version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: scrap_db
    environment:
      POSTGRES_USER: ozzurep
      POSTGRES_PASSWORD: marij
      POSTGRES_DB: scrap
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my_custom_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ozzu@proton.me
      PGADMIN_DEFAULT_PASSWORD: marij
    ports:
      - '8080:80'
    depends_on:
      - postgres
    networks:
      - my_custom_network

volumes:
  pg_data:

networks:
  my_custom_network:
    driver: bridge
